[project]
name = "streamlit_mermaid_interactive"
# The real package version is in the root pyproject.toml file
version = "0.1.0"

[[tool.streamlit.component.components]]
name = "mermaid"
asset_dir = "frontend"
